name: gac
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python==3.7
  - pip
  - pytorch==1.10.1
  - torchvision==0.11.2
  - torchaudio==0.10.1
  - cudatoolkit==11.3.1
  - absl-py
  - pyparsing
  - jupyterlab
  - scikit-image
  - pip:
    - termcolor
    - git+https://github.com/deepmind/dm_control.git
    - git+https://github.com/denisyarats/dmc2gym.git
    - tb-nightly
    - imageio
    - imageio-ffmpeg
    - git+https://github.com/facebookresearch/hydra@0.11_branch
    - pandas
    - ipdb
    - tqdm
    - yapf
    - mujoco_py
    - sklearn
    - matplotlib
    - kornia
    - future
    - gym==0.21.0
    - setuptools==59.5.0
